import type { NextPage,  } from 'next';
import Head from 'next/head';
import {apiGetJustAdded, apiGetRecentlyAdded } from 'pages/api/dashboard';
import { getTokenFromCookie } from 'src/_constant';
import { useSelector } from 'react-redux';
import { wrapper } from 'src/store';
import { ACCESS_TOKEN_SUCCESS } from 'src/store/account';
import Dashboard from 'src/views/newdashboard/MainView';

const DashBoard: NextPage = () => {
  const lessonData = useSelector(state => {
    return state.dashboardNew.recentlyAddedData;
  });

  
  return (
    <div >
      <Head>
        <title>Dashboard | GoSwim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
       
        <Dashboard />
      </main>
    </div>
  )
}

export  const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    async () => {
    await  apiGetJustAdded(store.dispatch)
    if(store.getState().account.token)
    await  apiGetRecentlyAdded(store.dispatch)

          // store.dispatch()
  return {
    props: {}, // will be passed to the page component as props
  } 
}
);
export default DashBoard



