import type { NextPage } from 'next';
import CreateViewLessons from 'pages/app/admin/lessons/create/index';
import { wrapper } from 'src/store';
import Head from 'next/head';


const Edit: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Admin |  Edit Lessons</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CreateViewLessons />
      </main>
    </div>
  )
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    async (context) => {
      return {
        props: {}, // will be passed to the page component as props
      }
    }
);

export default Edit;
