import type { NextPage } from 'next';
import Head from 'next/head';
import Router from 'next/router';
import { apiGetSubscriptionProducts } from 'pages/api/subscriptions';
import { wrapper } from 'src/store';
import SignUpView from 'src/views/goswim/auth/SignUp';

const SignUpPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Sign up | GoSwim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <SignUpView />
      </main>
    </div>
  )
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    async (context) => {
      const { planID } = context.query;
      if(planID){
        await apiGetSubscriptionProducts(store.dispatch);
      }else{
        if (context.res) {
          context.res.writeHead(302, { location: '/plans' });
          context.res.end();
        }
        else {
          Router.push(`/plans`);
        }
      }
      
      return {
        props: { }, // will be passed to the page component as props
      }
    }
);

export default SignUpPage