import type { NextPage } from 'next';
import Head from 'next/head';
import { wrapper } from 'src/store';
import PlanInfoPage from 'src/views/goswim/static/plan_info';

const SubscriptionInfo: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Subscription Info | GoSwim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main > */}
  
      <PlanInfoPage />
      {/* </main> */}

    </div>
  )
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    async (context) => {

      return {
        props: {}, // will be passed to the page component as props
      }
    }
);
export default SubscriptionInfo
