import type { NextPage } from 'next';
import Head from 'next/head';
import { wrapper } from 'src/store';
import { ACCESS_TOKEN_SUCCESS } from 'src/store/account';
import { getTokenFromCookie } from 'src/_constant';
import AccountView from 'src/views/pages/AccountView';
import { apiGetAllTeamsList } from '../../api/groups';
import { apiGetUserProfile } from '../../api/account';

const AccountSettings: NextPage = () => {
    return (
        <div >
            <Head>
                <title>Account Settings | GoSwim</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main >
                <AccountView/>
            </main>

        </div>
    )
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    async (context) => {

      await apiGetUserProfile(store.dispatch)
      await apiGetAllTeamsList(store.dispatch)
      return {
        props: {}, // will be passed to the page component as props
      }
    }
);

export default AccountSettings
