import type { NextPage } from 'next';
import Head from 'next/head';
import { apiGetCourseDetail } from 'pages/api/courses';
import { apiGetLessons } from 'pages/api/lessons';
import { getTokenFromCookie } from 'src/_constant';
import { getLessonArgs } from 'src/constants';
import { wrapper } from 'src/store';
import { ACCESS_TOKEN_SUCCESS } from 'src/store/account';
import CourseDetailsView from 'src/views/goswim/courses/MainView/details';

const CourseDetails: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Course-Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <CourseDetailsView />
      </main>
    </div>
  )
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
  async(context) =>{
    const {courseId} = context.query;
    const courseLessonReq : getLessonArgs = 
    {isAdmin: false,
  isBasic: false,
  pageID: 1,
  limit: 12,
  course_id: courseId
}

      if(courseId)
      await apiGetCourseDetail(store.dispatch,courseId);

      await apiGetLessons(store.dispatch,courseLessonReq )

      return {
        props:{}
      }
  }
)

export default CourseDetails
