import type { NextPage } from 'next';
import Head from 'next/head';
import { wrapper } from 'src/store';
import SignIn from 'src/views/goswim/auth/SignIn';

const SignInPage: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Sign in | GoSwim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <SignIn />
      </main>
    </div>
  )
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    async () => {
      return {
        props: {}, // will be passed to the page component as props
      }
    }
);

export default SignInPage
