import type { NextPage } from 'next';
import Head from 'next/head';
import { apiGetSubscriptionProducts } from 'pages/api/subscriptions';
import { wrapper } from 'src/store';
import PlansView from 'src/views/goswim/Subscriptions';

const PlansPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Plans</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PlansView />
      </main>
    </div>
  )
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    async (context) => {
      await apiGetSubscriptionProducts(store.dispatch);
      return {
        props: { }, // will be passed to the page component as props
      }
    }
);

export default PlansPage