import type { NextPage } from 'next';
import Head from 'next/head';
import { apiGetFavourites } from 'pages/api/favourites';
import { apiGetGroups } from 'pages/api/groups';
import { getTokenFromCookie } from 'src/_constant';
import { wrapper } from 'src/store';
import { ACCESS_TOKEN_SUCCESS } from 'src/store/account';
import FavoriteView from 'src/views/goswim/lessons/Favorites';

const Favorites: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Favorites | GoSwim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
      <FavoriteView />
      </main>

    </div>
  )
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    async (context) => {

      await apiGetFavourites(store.dispatch);

  return {
    props: {}, // will be passed to the page component as props
  } 
}
);

export default Favorites
