import type { NextPage } from 'next';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import { wrapper } from 'src/store';

const BillingView = dynamic(() => import('src/views/pages/Billing'), {ssr: false });


const Billing: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Billing | GoSwim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
  
      <BillingView />
      </main>

    </div>
  )
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    async (context) => {

      return {
        props: {}, // will be passed to the page component as props
      }
    }
);
export default Billing
