import type { NextPage } from 'next';
import Head from 'next/head';
import { apiGetCourseDetail } from 'pages/api/courses';
import { wrapper } from 'src/store';
import CourseDetailsView from 'src/views/goswim/courses/MainView/details';

const Tutorials: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Tutorials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
  
      <CourseDetailsView />
      </main>

    </div>
  )
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
  async(context) =>{
    const {_id} = context.query
      if(_id && typeof  _id == 'string')
      await apiGetCourseDetail(store.dispatch,_id)

      return {
        props:{}
      }
  }
)

export default Tutorials
