import type { NextPage } from 'next';
import EditMember from 'src/views/management/Members/CreateEditView';
import { wrapper } from 'src/store';
import Head from 'next/head';


const Edit: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Admin | Users</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <EditMember />
            </main>
        </div>
    )
}

export const getServerSideProps = wrapper.getServerSideProps(
    (store) =>
        async (context) => {
            
            return {
                props: {}, // will be passed to the page component as props
            }
        }
);

export default Edit;
