import type { NextPage } from 'next';
import Head from 'next/head';
import { apiGetLessons, apiGetLessonsFilterData } from 'pages/api/lessons';
import { getTokenFromCookie } from 'src/_constant';
import { getLessonArgs } from 'src/constants';
import { wrapper } from 'src/store';
import { ACCESS_TOKEN_SUCCESS } from 'src/store/account';
import Lessons from 'src/views/goswim/lessons/MainView';

const LessonsView: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Lessons | GoSwim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Lessons />
      </main>
    </div>
  )
}

export  const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    async (context) => {
      const {stroke, expertise, tags, search} = context.query;
      let args:getLessonArgs = {pageID: 1, limit: 12, isAdmin: false, isBasic:false, stroke:stroke?stroke :null, expertise: expertise?expertise:null, tags:tags?tags: null, search:search?search:null  }
     
      await apiGetLessonsFilterData(store.dispatch,'Lesson')
      await apiGetLessons(store.dispatch, args)

  return {
    props: {}, // will be passed to the page component as props
  } 
}
);

export default LessonsView;