import type { NextPage } from 'next';
import Head from 'next/head';
import dynamic from 'next/dynamic';
import { wrapper } from 'src/store';

const WeeklyThemes = dynamic(() => import('src/views/goswim/admin/WeeklyThemes'), {ssr: false });

const WeeklyTheme: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Admin | WeeklyTheme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <WeeklyThemes />
      </main>
    </div>
  )
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    async (context) => {
    
      return {
        props: {}, // will be passed to the page component as props
      }
    }
);

export default WeeklyTheme;
