import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import dynamic from 'next/dynamic';
import { wrapper } from 'src/store';
const MemberDetailView = dynamic(import(`../../../src/views/management/Members/CreateEditView`), {ssr: false})  

const MemberEdit: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Member Edit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <MemberDetailView />
      </main>
    </div>
  )
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    async (context) => {

      return {
        props: {}, // will be passed to the page component as props
      }
    }
);

export default MemberEdit;