import type { NextPage } from 'next';
import Head from 'next/head';
import ThemeOfTheWeek from 'src/views/goswim/ThemeOfTheWeek';
import { wrapper } from 'src/store';
import { ACCESS_TOKEN_SUCCESS } from 'src/store/account';
import { getTokenFromCookie, gsTimezoneValue } from 'src/_constant';
import { apiGetThemeOfTheWeek } from 'pages/api/themeoftheweek';

const WeeklyTheme: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Theme of the week | GoSwim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >

        <ThemeOfTheWeek />
      </main>

    </div>
  )
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    async (context) => {
      const scheduled_on = new Date().valueOf();
      const timeZone = context.req.cookies[gsTimezoneValue]
  
      await apiGetThemeOfTheWeek(store.dispatch, scheduled_on, timeZone)
      return {
        props: {}, // will be passed to the page component as props
      }
    }
);

export default WeeklyTheme
