import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import { wrapper } from '../../../../src/store';
import ForgotPasswordView from '../../../../src/views/goswim/auth/ForgotPassword';

const ForgotPasswordPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ForgotPasswordView />
      </main>
    </div>
  )
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    async () => {
      return {
        props: {}, // will be passed to the page component as props
      }
    }
);

export default ForgotPasswordPage;