import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { wrapper } from '../../src/store';
import { ACCESS_TOKEN_SUCCESS } from '../../src/store/account';
import TodaysLessonPage from '../../src/views/goswim/groups/TodaysLesson';
import { getTokenFromCookie } from 'src/_constant';

const TodaysLesson: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Groups | GoSwim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TodaysLessonPage />
    </div>
  )
}


export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    async (context) => {
      const token = await getTokenFromCookie(context.req);
      // const args = { page: 1, limit: 20, search: '' }
      await store.dispatch({
        type: ACCESS_TOKEN_SUCCESS,
        payload: { token }
      });
      // await apiGetGroups(store.dispatch, args);

      return {
        props: {}, // will be passed to the page component as props
      }
    }
);

export default TodaysLesson;