import type { NextPage } from 'next';
import Head from 'next/head';
import { apiGetGroups } from 'pages/api/groups';
import { wrapper } from 'src/store';
import GroupsPage from 'src/views/management/Teams/MainView/index';

const Groups: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Groups | GoSwim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GroupsPage />
    </div>
  )
}


export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    async (context) => {
      const args = { page: 1, limit: 20, search: '' }
      await apiGetGroups(store.dispatch,args);

  return {
    props: {}, // will be passed to the page component as props
  } 
}
);

export default Groups
